# Generated by Django 3.0.7 on 2024-04-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VCS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='mobile',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
