# Generated by Django 3.0.7 on 2024-04-18 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VCS', '0002_students_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='mobile',
        ),
    ]
